import TopicState from "@/context/Topic/TopicState";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthState from "@/context/Auth/AuthState";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthState>
        <TopicState>
          <body className=''>
            <Navbar />
            {children}
          </body>
        </TopicState>
      </AuthState>
    </html>
  );
}
